version: "3.8"
services:
  tensorflow-serving:
    image: "tensorflow/serving"
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - type: bind
        source: models/t5.1.1.xxl_ssm_wq
        target: /models/t5.1.1.xxl_ssm_wq/1
    environment:
      MODEL_NAME: t5.1.1.xxl_ssm_wq
