version: "3.8"
services:
  tensorflow-serving:
    image: "tensorflow/serving"
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - type: bind
        source: t5.1.1.xxl
        target: /models/t5.1.1.xxl/1
    environment:
      MODEL_NAME: t5.1.1.xxl
